include: package:yumemi_lints/dart/3.3/recommended.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    # https://pub.dev/packages/freezed
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: false
